#!/usr/bin/env bash
# Takes 'domain' and 'subdomain' parameters and displays information for the specified subdomain

domain=$1
subdomain=$2

subdomains=( "www" "lb-01" "web-01" "web-02")

DomainInfo () {
	script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER SECTION:')
	S_DOMAIN=$(echo "$script" | awk -F "." '{print $1}')
	R_TYPE=$(echo "$script" | awk '{print $4}')
	DEST=$(echo "$script" | awk '{print $5}')
	echo "The subdomain $S_DOMAIN is a $R_TYPE record and points to $DEST"
}

if [ "$#" -eq 2 ]
then
	DomainInfo "$domain" "$subdomain"
else
	for subdomain in "${subdomains[@]}"
    do
		DomainInfo "$domain" "$subdomain"
	done
fi
