#!/usr/bin/env bash
# Bash script that configures your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a \
          error_page 404 /custom_404.html;\n\
          location = /custom_404.html {\n\
             internal;\n\
          }' /etc/nginx/sites-available/default
sudo service nginx restart