#!/usr/bin/env bash
# this is a script that gives you information about the school file

if [ -e "school" ]
then
    echo "school file exists"
else
    echo "school file does not exist"
	exit 1
fi

if [ ! -s "school" ]
then
    echo "school file is empty"
elif [ -f "school" ]
then
    echo "school is a regular file"
else
    echo "school file is not empty"
fi
